from . import sale_order
from . import account_move
from . import account_payment
from . import stock
from . import purchase_order
from . import product_template
from . import crm_lead
from . import res_partner
from . import hr_employee
from . import helpdesk_ticket
from . import self_heal
